version: '3.7'
services:
  my-db:
    privileged: true
    devices:
    - "/dev/fuse:/dev/fuse"
    build: .
    image: postgresql12-3-alpine
    container_name: my-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432